README.md
improve readme.md
title: improve readme.md
=> improve: readme.md

.github/workflows/code-linting.yml, package.json, tailwind.config.js
Add code linting on pull requests to main
title: feat code linting on pull request
=> feat: code linting on pull request

error.vue, layouts/public.vue, middleware/auth.global.ts
- add middleware to check token in cookie, if no token available throw Unauthorized Error
- add `auth.global.ts` middleware
- add `public` layout
- add 401 unauthorized error page
title: feat auth middleware
participants: @Ibwedagama @rizfirman @agunghide @yoslie
=> feat: auth middleware

.eslintrc.cjs, common/helpers/cookie.ts, components/Loading/Overlay.vue, components/Loading/Spinner.vue, error.vue, layouts/default.vue, layouts/public.vue, middleware/auth.global.ts, middleware/verify-token.ts, package.json, pages/verify/[token].vue, pnpm-lock.yaml, stores/loading.ts, stores/site.ts
- add `verify` page to store token and site id
- add `verify-token` middleware
- add `LoadingOverlay` component 
- [list of related tasks or issues](https://app.clickup.com/t/860qpf4p7)
title: feat j-site auth flow
participants: @Ibwedagama @yoslie @agunghide @doohanas
=> feat: j-site auth flow

components/TheHeader.vue
- fix logout redirect url
title: fix logout redirect url
participants: @Ibwedagama @rizfirman @yoslie
=> fix (logout): change logout redirect url

middleware/verify-token.ts, nuxt.config.ts, package.json, pnpm-lock.yaml, stores/site.ts
fix the missing site ID value on `site` store and add `pinia persisted-state` plugin
title: fix missing site id
participants: @Ibwedagama @yoslie @doohanas
=> fix: missing site id

components/SidebarSiteSelect.vue, components/TheSidebar.vue
- improve sidebar navigation item scroll style
- add redirect URL to `Kelola J-Site` button
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/521642c1-536f-460e-bec9-86197385263d
- [[CMS - Navigasi] Navigasi kelola j-site dari builder belum berfungsi](https://app.clickup.com/t/86cttpgpg)
- [[CMS - Navigasi] Styling scroll bar manu belum sesuai](https://app.clickup.com/t/86cttv8fw)
title: refactor: improve sidebar
participants: @Ibwedagama @rizfirman @agunghide @rayfajars @yoslie
=> refactor: improve sidebar

components/HeaderMenu.vue, components/SidebarSiteSelect.vue, components/TheSidebar.vue, layouts/default.vue, layouts/public.vue, middleware/verify-token.ts, pages/verify/[token].vue, plugins/j-site-api.ts, repository/j-site/modules/settings.ts, repository/j-site/types/settings.ts, stores/site.ts
Fix middleware bug that makes initial network request failed because Bearer Token `undefined`. Get available sites based on login user, set the global `Site ID` when user change active site.
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/f4241ab8-3057-4770-8d89-4c83253bb54f
- [S3A1 - Navigasi](https://app.clickup.com/t/860qqqb1g)
title: feat get available sites
=> feat: get available sites

components/SidebarSiteSelect.vue, components/TheSidebar.vue
fix styling on sidebar site select 
title: fix styling on sidebar site select
=> style (site-select): fix styling on sidebar site select

nuxt.config.ts
fix google font weight
title: fix google fonts weight
participants: @Ibwedagama @marsellavaleria19 @rizfirman @yoslie
=> fix (nuxt.config): google fonts weight

components/Page/AsideCreate.vue, components/Page/HeaderCreate.vue
- add max length input title page
- temporary disabled button preview site
title: update create page (add max length input title page, temporary disabled button preview site)
participants: @yoslie @doohanas @agunghide @marsellavaleria19
=> update create page (add max length input title page, temporary disabled button preview site)

components/ProgressModal.vue, components/Widget/Gallery.vue
feat: create handle upload and delete image in widget gallery
- Update background-color for progress-modal component
- handle delete image
- handle upload image
https://github.com/jabardigitalservice/j-site-builder/assets/79241754/98723c5e-68da-450b-ad83-63f83a00e3f5
[S7A5 - Membuat Widget Gallery](https://app.clickup.com/t/9003239225/CES-1462)
title: feat: create handle upload and delete image in widget gallery
participants: @doohanas @Ibwedagama @yoslie @marsellavaleria19
=> feat: create handle upload and delete image in widget gallery

components/Widget/Slideshow.vue
add a tooltip when the upload button is disabled
[S7A1 - Membuat Widget Slideshow](https://app.clickup.com/t/9003239225/CES-1458)
title: feat slideshow add disabled upload button tooltip
participants: @Ibwedagama @rizfirman @rayfajars @yoslie
=> feat (slideshow): add disabled upload button tooltip

components/Widget/Gallery.vue
feat: add image validation in widget gallery
- change information text
- add image validation 
https://github.com/jabardigitalservice/j-site-builder/assets/79241754/af98181f-6f8c-40a3-9968-96004de478e6
[S7A5 - Membuat Widget Gallery](https://app.clickup.com/t/9003239225/CES-1462)
title: feat: add image validation in widget gallery
participants: @doohanas @Ibwedagama
=> feat: add image validation in widget gallery

components/Widget/Slideshow.vue
- add close button action
- adjust behavior on modal closing
- [T016 - Memperbaiki fungsi tombol x "close" pada popup delete image slideshow](https://app.clickup.com/t/9003239225/CES-2865)
title: fix close button on slideshow delete modal
participants: @Ibwedagama @sheilaazhara @doohanas @marsellavaleria19
=> fix (slideshow): add close button action on delete modal

app.config.ts, components/ProgressModal.vue
- Change progress element into UProgress component nuxt ui in progress-modal
https://github.com/jabardigitalservice/j-site-builder/assets/79241754/fdf3b158-f95b-4d18-81d1-88ec987a1b46
- [S5A5 - Membuat Add Page (Costumize Template)](https://app.clickup.com/t/9003239225/CES-1307)
title: refactor: change progress element into UProgress component nuxt ui in progress-modal
participants: @doohanas @Ibwedagama
=> refactor: change progress element into UProgress component nuxt ui in progress-modal

components/Widget/PostCrawler.vue
update style scrollbar preview post to transparent
[T020 - Memperbaiki styling scroll bar](https://app.clickup.com/t/9003239225/CES-2912)
title: update style scrollbar preview post in widget post crawler setup content
participants: @yoslie @Ibwedagama
=> style: update style scrollbar preview post

pages/halaman/buat.vue
change function back and save draft
[T022 - Memperbaiki fungsi tombol "kembali dan simpan draft"](https://app.clickup.com/t/9003239225/CES-2929)
title: change function back and save draft button confirmation in header page create
participants: @yoslie @Ibwedagama
=> update: change function back and save draft

components/Widget/Agenda.vue, repository/j-site/types/template.ts
fix data type of `is_active` payload
https://app.clickup.com/t/9003239225/CES-1461
title: change type of formdata isActive
participants: @Ibwedagama @sheilaazhara @yoslie
=> fix (agenda): change type of form data isActive

components/Page/ModalBuilderInputTitle.vue
-Fix mutating state in store on clear button
https://github.com/jabardigitalservice/j-site-builder/assets/79241754/f670d7f7-ed5b-4fdc-966d-3e193a8df4a8
[S5A6 - Membuat Add Page (Manage Section)](https://app.clickup.com/t/9003239225/CES-1422)
title: fix: remove action to mutate title and desc on clear button
participants: @doohanas @yoslie @rizfirman
=> fix: remove action to mutate title and desc on clear button

components/Page/ModalBuilderInputTitle.vue
- refactor: add max-length for title and description
[T027 - Memperbaiki counting dan menghapus pesan validasi](https://app.clickup.com/t/9003239225/CES-3008)
title: refactor: add max-length for title and description
participants: @doohanas @rizfirman @yoslie
=> refactor: add max-length for title and description

components/SearchBar.vue, components/Widget/Showcase/AddEditForm.vue, components/Widget/Showcase/ModalSelectLogo.vue, components/Widget/Showcase/index.vue, pages/halaman/semua.vue, plugins/j-site-api.ts, repository/j-site/modules/logo.ts, repository/j-site/types/logo.ts
update popup setting content widget showcase: add modal select logo from api
- create nested modal select logo from api in modal add item showcase widget
- replace dummy data showcase to added data showcase
- store data payload widget
- minor update style width searchbar component
https://github.com/jabardigitalservice/j-site-builder/assets/65396086/6bca6c26-5dd7-4226-ae61-198b5b87bef5
[Membuat Fungsional Tambah Gambar via pilih logo](https://app.clickup.com/t/9003239225/CES-2936)
title: update popup setting content widget showcase: create nested modal select logo from api in modal add item showcase widget
participants: @yoslie @doohanas @Ibwedagama @marsellavaleria19
=> Update/widget showcase - modal select logo

components/Widget/WYSIWYG.vue, package.json, pnpm-lock.yaml
- handle image upload and validation
- handle data binding to page store
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/506a9304-8229-40d7-86b6-eb5d938d1c6b
[S7A7 - Membuat Widget WYSWYG (Text & Image)](https://app.clickup.com/t/9003239225/CES-1467)
title: feat wysiwyg data binding and upload handler
participants: @Ibwedagama @doohanas
=> feat: wysiwyg data binding and upload handler

common/constant/navigation.js, pages/posting.vue, pages/posting/arsip.vue, pages/posting/draft.vue, pages/posting/semua.vue, pages/posting/terbit.vue
add structure index feature post
title: add structure index feature post
participants: @yoslie @doohanas @agunghide @Ibwedagama @marsellavaleria19
=> feat: add structure index feature post

repository/j-site/modules/logo.ts, repository/j-site/modules/media.ts, repository/j-site/modules/settings.ts
- fix module export for each repository
title: fix repository module export
=> fix: repository module export

components/Base/Dropzone.vue
- feat (dropzone): slicing layout dropzone component
title: refactor: add max-length for title and description
participants: @doohanas @Ibwedagama @yoslie
=> feat (dropzone): slicing layout dropzone component

components/Loading/ListSkeleton.vue, pages/posting/arsip.vue, pages/posting/draft.vue, pages/posting/semua.vue, pages/posting/terbit.vue
refactor loading skeleton post list
title: refactor loading skeleton post list
participants: @yoslie @doohanas
=> refactor: refactor loading skeleton post list

pages/posting/arsip.vue, pages/posting/draft.vue, pages/posting/terbit.vue
- feat: to search input based on title for all items in  terbit, draft, and arsip tabs
[S4A2 - Membuat Search Post](https://app.clickup.com/3808590/v/b/6-175624479-2)|
title: feat: to search input based on title for all items in  terbit, draft, and arsip tabs
participants: @doohanas @yoslie
=> feat: to search input based on title for all items in  terbit, draft, and arsip tabs

components/Post/List.vue, pages/posting/semua.vue, pages/posting/terbit.vue, repository/j-site/modules/post.ts
update action archive post in list post (all post and published post)
title: update action archive post in list post (all post and published post)
participants: @yoslie
=> feat: archive post in list post all and published

.vscode/settings.json, components/Widget/Showcase/AddEditForm.vue
add validation isEditMode to delete image
[T038 - Memperbaiki error hapus media pada saat edit showcase](https://app.clickup.com/t/9003239225/CES-3463)
title: add validation isEditMode to delete image in setup widget showcase
participants: @yoslie @doohanas @rayfajars
=> update: add validation isEditMode to delete image

components/Post/List.vue
hide feature duplicate and pinned action list post
title: hide feature duplicate and pinned action list post
participants: @yoslie @doohanas @rayfajars
=> update: hide feature duplicate and pinned action list post

components/Post/Form.vue, stores/post.ts
binding form title, content, and author to page store
title: feat post form data binding
participants: @Ibwedagama @rizfirman @sheilaazhara @agunghide 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzAzODE4NzAyMDU4LTAuNjY2OTEzMzY0NzQ5NjIyOC53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9Q1F5Um1QRTBrdkpqa0h0ZyUyRjIwMjMxMjI5JTJGYXNpYS1zb3V0aGVhc3QyLWElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDAyNTgyMlomWC1BbXotRXhwaXJlcz02MDQ4MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JlgtQW16LVNpZ25hdHVyZT02MzJhMjk5NjNhYTIyZmM5ZDdiYzUxODUyNjMyMjBiM2M5MTM5ODI1NTY2OGNkMjQ1Yjc4YzVmNTNmZjNjMDlk
=> feat: post form data binding

components/Post/Form.vue
- handle image upload and validation on post content
- handle upload error
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/69ba2f31-94df-44bc-b707-73d87a043ae3
title: feat handle image upload on post content
participants: @Ibwedagama @marsellavaleria19 @sheilaazhara @agunghide @doohanas 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzA0MjQ4NTI3Njg5LTAuOTMzNTQ0Mzc1NjM3MzEyMS53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9Q1F5Um1QRTBrdkpqa0h0ZyUyRjIwMjQwMTAzJTJGYXNpYS1zb3V0aGVhc3QyLWElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMjIwN1omWC1BbXotRXhwaXJlcz02M …
=> feat: handle image upload on post content

components/Post/Form.vue
- refactor method `handleContentImageUpload`
title: refactor handle content image upload
participants: @Ibwedagama @marsellavaleria19 @agistyaanugrah @rayfajars @yoslie 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzA0MzQwODU4NTgyLTAuMDQxNDg2MDcxMDM0NjYyNzMud2VicD9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUNReVJtUEUwa3ZKamtIdGclMkYyMDI0MDEwNCUyRmFzaWEtc291dGhlYXN0Mi1hJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQwNDAwNThaJlgtQW16LUV4cGlyZXM9NjA0ODAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZYLUFtei1TaWduYXR1cmU9ZmIyOTlkMDA1OGExY2VlNTAwZGI5NjMwZWRkZTk1ZmJhYWY5NzIxMmFlNWI5NTA4NmJiYzY1YjRjZj …
=> refator (post): handle content image upload

components/Post/Form.vue, plugins/j-site-api.ts, repository/j-site/modules/category.ts, repository/j-site/types/category.ts
handle CRUD mechanism of categories
- handle fetch categories from API
- handle create, update, delete category
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/7c60c3e3-078e-499b-9fab-fe8c174eb9fc
title: feat fetch create update delete category on post form
participants: @Ibwedagama @yoslie @doohanas 
screenshot: https://file-generator.digitalservice.id/download?url=aHR0cHM6Ly9maWxlLmRpZ2l0YWxzZXJ2aWNlLmlkL2RpZ2l0ZWFtLXB1YmxpYy8xNzA0MzUzNDA4NTg3LTAuNjcyNzc0OTA5NzIwOTgzNC53ZWJwP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9Q1F5Um1QRTBrdkpqa0h0ZyUyRjIwMjQwMTA0JTJGYXNpYS1zb3V0aGVhc3QyLWElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDA3MzAwOFomWC1BbXo …
=> feat: fetch, create, update, delete category on post form

components/Post/Form.vue, components/Widget/Gallery.vue, components/Widget/Showcase/AddEditForm.vue, components/Widget/Slideshow.vue, components/Widget/WYSIWYG.vue
refactor file upload caption and remove category attribute body 
title: refactor file upload caption and remove category attribute body
participants: @yoslie @Ibwedagama @doohanas
=> update: refactor file upload caption attribute body

components/Post/Form.vue, package.json, plugins/j-site-api.ts, pnpm-lock.yaml, repository/j-site/modules/tag.ts, repository/j-site/types/tag.ts, stores/post.ts
- handle add, delete and tag suggestions
- add tag repository
- handle create tags
- handle remove tags
- fetch tag suggestions
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/4176f03b-2257-479c-8b09-8eab7a87d389
title: feat posting handle tags
participants: @Ibwedagama @yoslie @doohanas 
screenshot: https://lnk.digiteam.id/Z8v2pg
=> feat: posting handle tags

components/FilterBar.vue, components/InputCalendar.vue
- [S4A3 - Membuat Filter Post](https://app.clickup.com/t/9003239225/CES-2933)
- Change modal component for Filter modal
- Handle validation for input calendar
[AwesomeScreenshot-1_8_2024,4 41 17PM.webm](https://github.com/jabardigitalservice/j-site-builder/assets/79241754/c40972d1-c7b9-442a-8f63-60762ba665f9)
title: feat: add validation for datepicker in filter bar
participants: @doohanas @Ibwedagama @yoslie
=> feat: add validation for datepicker in filter bar

components/Widget/Showcase/AddEditForm.vue, components/Widget/Showcase/Dropzone.vue, components/Widget/Showcase/ModalSelectLogo.vue, components/Widget/Showcase/index.vue
[add data cy on setup widget showcase](https://github.com/jabardigitalservice/j-site-builder/commit/c46813142f4129efa60a1d303f218b7c7f93799a)
[Q1A7 - Membuat test script feature widget showcase](https://app.clickup.com/t/9003239225/CES-4216)
title: add data cy on setup widget showcase
participants: @yoslie @azhargraha @doohanas @marsellavaleria19 @Ibwedagama
=> update: add data cy on setup widget showcase

components/Post/Form.vue, components/Post/FormCategory.vue, components/Post/FormTags.vue, package.json, pages/posting/buat.vue, pnpm-lock.yaml
- bump nuxt/ui version to v.2.12.0
- disable Submit button if form invalid
- improve form validation
title: feat improve post form validation
participants: @Ibwedagama @yoslie @doohanas 
screenshot: https://lnk.digiteam.id/gPfhUt
=> feat: improve post form validation

components/FilterBar.vue, pages/posting/index.vue
- [T048 - Memperbaiki behavior batal menerapkan filter](https://app.clickup.com/3808590/v/b/6-175624479-2/)
- Fix behavior search and filter for each change tab
- add disabled condition in submit button
https://github.com/jabardigitalservice/j-site-builder/assets/79241754/17da16ff-ec50-406f-b1bd-24e935a76b59
title: fix (filter): change cancel behaviour when user selected filter and add disabled condition
participants: @doohanas @yoslie @azhargraha @sheilaazhara
=> fix (filter): change cancel behaviour when user selected filter and add disabled condition

components/Post/Form.vue, pages/posting/buat.vue
- improve validation on post author
- handle save as published
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/9fe951c6-1d17-47d9-8dec-948a6baac83e
[S4A5 - Mengimplementasikan Status Post](https://app.clickup.com/t/9003239225/CES-2956)
title: feat posting handle save as published
participants: @Ibwedagama @sheilaazhara @azhargraha @yoslie 
screenshot: https://lnk.digiteam.id/QrdeeZ
=> feat: posting save as publish

assets/css/tailwind.css, components/Post/FormCategory.vue, components/Post/FormImage.vue, components/Post/FormTags.vue, components/Post/FormTitle.vue, pages/posting/index.vue
Fix Post Form issue tickets
- [T059 - Memperbaiki tampilan tag yang panjang](https://app.clickup.com/t/9003239225/CES-4695)
- [T055 - Memperbaiki pesan validasi yang tidak sesuai ketika input nama penulis valid](https://app.clickup.com/t/9003239225/CES-4687)
- [T051 - Memperbaiki fungsi tombol kembali di form add post](https://app.clickup.com/t/9003239225/CES-4675)
- [T054 - Memperbaiki label nama pada image yang telah berhasil diupload](https://app.clickup.com/t/9003239225/CES-4686)
- [T056 - Menambahkan pesan validasi/counting sisa karakter ketika user edit kategori >125 karakter](https://app.clickup.com/t/9003239225/CES-4692)
- [T052 - Memperbaiki penamaan tombol add post](https://app.clickup.com/t/9003239225/CES-4678)
- [T057 - Memperbaiki styling scroll bar di form kategori …
=> refactor: post form validation, label and error mesage

components/FilterBar.vue, pages/posting/index.vue
- [T046 - Memperbaiki tampilan popup filter post](https://app.clickup.com/3808590/v/b/6-175624479-2/)
- [T050 - Melakukan reset halaman data hasil filter post ke page 1](https://app.clickup.com/t/9003239225/CES-4610)
- [T049 - Melakukan reset page data hasil pencarian ke page 1](https://app.clickup.com/t/9003239225/CES-4609)
- change width modal filter 
- Reset page after search and filter
title: fix: change width modal filter and reset page after search and filter
participants: @doohanas @marsellavaleria19 @rayfajars @azhargraha @Ibwedagama
=> fix: change width modal filter and reset page after search and filter

components/FilterBar.vue
- [T047 - Memperbaiki validasi range tanggal](https://app.clickup.com/t/9003239225/CES-4557)
- fix validation on start and end date input
title: fix: validation input date filter post
participants: @doohanas @yoslie @Ibwedagama
=> fix: validation input date filter post

components/Post/FormCategory.vue
- add name attribute to edit category form to prevent global validation
[T060 - Memperbaiki pesan validasi yang muncul ketika melakukan perubahan kategori](https://app.clickup.com/t/9003239225/CES-4747)
title: fix add name to edit category input field
participants: @Ibwedagama @azhargraha @rayfajars @doohanas 
screenshot: https://lnk.digiteam.id/DcPBqU
=> fix (post): add name to edit category input field to prevent validation

components/FilterBar.vue
- [T047 - Memperbaiki validasi range tanggal](https://app.clickup.com/t/9003239225/CES-4557)
- refactor: accept validation start and end date on same date
title: refactor: accept validation start and end date on same date
participants: @doohanas @Ibwedagama @marsellavaleria19 @azhargraha @rayfajars
=> refactor: accept validation start and end date on same date

components/Post/List.vue
- fix validation on start and end date input
title: refactor (post-list): add default text when value is falsy
participants: @doohanas @yoslie @Ibwedagama
=> refactor (post-list): add default text when value is falsy

pages/halaman/index.vue
add search function into list page
title: add search function into list page
participants: @yoslie @Ibwedagama @doohanas @azhargraha
=> feat: add search function into list page

pages/posting/index.vue
- refactor: add debounce method to delay state update 500 ms
title: refactor (posting-page): add debounce method to delay state update 500 ms
participants: @doohanas @agunghide @azhargraha @yoslie @Ibwedagama
=> refactor (posting-page): add debounce method to delay state update 500 ms

components/HeaderMenu.vue
- add z-index to header menu 
[T068 - Memperbaiki tampilan tombol yang saling bertabrakan di form add post](https://app.clickup.com/t/9003239225/CES-5124)
title: style add z-index to header menu
=> style (header-menu): add z-index 50 to header menu options

pages/posting/buat.vue
- reset post form data before unmount
[T065 - Memperbaiki autofill data di form add post](https://app.clickup.com/t/9003239225/CES-5038)
title: fix reset poset store state before unmount
participants: @Ibwedagama @agunghide @yoslie 
screenshot: https://lnk.digiteam.id/FDGcZg
=> fix (post): reset post store state before unmount

pages/halaman/index.vue
change height section in list page
[T069 - Memperbaiki tampilan list data halaman melebihi section card](https://app.clickup.com/t/9003239225/CES-5140)
title: change height section in list page
participants: @yoslie @Ibwedagama @marsellavaleria19 @doohanas @azhargraha
=> fix: change height section in list page

pages/posting/ubah/[id].vue, stores/post.ts
Fixing defects on edit form feature
- fix accessing undefined property from nested object
- adjust button label and modal confirmation for post with status DRAFT
- adjust button label and modal confirmation for post with status PUBLISHED
https://github.com/jabardigitalservice/j-site-builder/assets/33661143/a6fe32bd-e3bb-4194-a9c2-af99c9c2be3e
[T070 - Memperbaiki nama tombol aksi dan pesan konfirmasi untuk post yang statusnya draft](https://app.clickup.com/t/9003239225/CES-5157)
[T071 - Memperbaiki tombol aksi untuk mengubah post yang belum memiliki kategori
](https://app.clickup.com/t/9003239225/CES-5158)
title: fix post edit form defects
participants: @Ibwedagama @marsellavaleria19 @azhargraha @yoslie
=> fix: post edit form defects

components/Post/Form.vue, components/Post/FormAuthor.vue, components/Post/FormCategory.vue, components/Post/FormContent.vue, components/Post/FormImage.vue, components/Post/FormTags.vue, components/Post/FormTitle.vue, pages/posting/buat.vue, pages/posting/ubah/[id].vue
as described by the title
- add data cy attribute on `buat.vue`, `ubah.vue` page
- add data cy attribute on `Form` component and it's children
- [Q1A10 - Membuat test script fitur tambah posting](https://app.clickup.com/t/9003239225/CES-4756)
title: feat add post form data cy attributes
participants: @Ibwedagama @azhargraha @yoslie 
screenshot: https://lnk.digiteam.id/wbW5oy
=> feat: add post form data cy atrribute

pages/posting/ubah/[id].vue
- fix conditional check for update post button
[T070 - Memperbaiki nama tombol aksi dan pesan konfirmasi untuk post yang statusnya draft](https://app.clickup.com/t/9003239225/CES-5157)
title: fix conditional check for update post button
participants: @Ibwedagama @sheilaazhara @doohanas @agunghide @azhargraha
=> fix (post): fix conditional check for update post button

components/Page/ModalChooseTemplate.vue, stores/page.ts
- Fix typescript error and Vue warn on `ModalChooseTempalate` component
- Fix type definition on `pageStore` state
title: fix choose template modal typescript error
participants: @Ibwedagama @marsellavaleria19 @rizfirman @sheilaazhara @agunghide @yoslie @doohanas
=> fix: choose template modal typescript error

components/Page/BuilderWidgetSelector.vue, components/Page/BuilderWidgetSelectorLayout.vue, stores/page.ts
change widget layout popover to select menu and bind into page strore
title: change widget layout popover to select menu and bind into page strore
participants: @yoslie @rizfirman @doohanas @agunghide @azhargraha @marsellavaleria19
=> update: change widget layout popover to select menu and bind into page strore

pages/halaman/buat.vue, pages/halaman/ubah/[id].vue
create publish page function and minor refactor
title: create publish page function and minor refactor
participants: @yoslie @doohanas @Ibwedagama @marsellavaleria19 @agunghide @azhargraha @rayfajars
=> update: create publish page function and minor refactor

components/Widget/PostCrawler.vue
set initial payload for widget post crawler
title: set initial payload for widget post crawler
participants: @yoslie @azhargraha @doohanas @Ibwedagama @marsellavaleria19
=> update: set initial payload for widget post crawler

components/Widget/Slideshow.vue
- refactor code structure; group state, method, and watcher based on context
- add default payload to store on create mode
- sync internal state with pageStore on edit mode
title: refactor improve slideshow state sync and code structure
participants: @Ibwedagama @rizfirman @azhargraha @yoslie @doohanas
=> refactor: improve slideshow state sync and code structure

components/Widget/Agenda.vue
- group states and methods based on context
- add initial payload on create mode
- set initial state on edit mode
title: refactor agenda widget
participants: @Ibwedagama @doohanas
=> refactor: agenda widget

components/Widget/Showcase/index.vue
set initial payload and sync store payload widget showcase
title: set initial payload and sync store payload widget showcase
participants: @yoslie @Ibwedagama @azhargraha @doohanas
=> update: set initial payload and sync store payload widget showcase

components/Widget/Gallery.vue
- refactor: improve state sync, code structure, and set style a new line
title: refactor: improve state sync, code structure, and set style a new line
participants: @doohanas @Ibwedagama @azhargraha @yoslie
=> refactor: improve state sync, code structure, and set style a new line

components/Widget/WYSIWYG.vue
set initial payload and sync store payload widget wysiwyg
title: set initial payload and sync store payload widget wysiwyg
participants: @yoslie @azhargraha @doohanas @Ibwedagama
=> update: set initial payload and sync store payload widget wysiwyg
